/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_iiitb_imageEffectApplication_libraryInterfaces_DominantInterface */

#ifndef _Included_com_iiitb_imageEffectApplication_libraryInterfaces_DominantInterface
#define _Included_com_iiitb_imageEffectApplication_libraryInterfaces_DominantInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_iiitb_imageEffectApplication_libraryInterfaces_DominantInterface
 * Method:    applyDominant
 * Signature: ([[Lcom/iiitb/imageEffectApplication/libraryInterfaces/Pixel;)[[Lcom/iiitb/imageEffectApplication/libraryInterfaces/Pixel;
 */
JNIEXPORT jobjectArray JNICALL Java_com_iiitb_imageEffectApplication_libraryInterfaces_DominantInterface_applyDominant
  (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
